import fs from 'fs';
import path from 'path';

/**
 * Generates a model introspection schema
 */
export class FunctionModelIntrospectionSchemaGenerator {
  private readonly header =
    '// This file is auto-generated by Amplify. Edits will be overwritten.';

  private misFilePath: string;

  private indentation: string = '  ';

  /**
   * Initialize model introspection schema file name and location
   */
  constructor(private readonly functionName: string) {
    this.misFilePath = `${process.cwd()}/.amplify/generated/model-introspection-schema/${
      this.functionName
    }.json`;
  }
  /**
   * Generate a model introspection schema
   */
  generateModelIntrospectionSchema = (modelIntrospectionSchema: string) => {
    this.writeFile(modelIntrospectionSchema);
  };

  private writeFile = (content: string) => {
    const misFileDirname = path.dirname(this.misFilePath);

    if (!fs.existsSync(misFileDirname)) {
      fs.mkdirSync(misFileDirname, { recursive: true });
    }

    fs.writeFileSync(this.misFilePath, content);
  };
}
