import fs from 'fs';
import path from 'path';

/**
 * Generates a model introspection schema
 */
export class FunctionModelIntrospectionSchemaGenerator {
  private readonly header =
    '// This file is auto-generated by Amplify. Edits will be overwritten.';

  private misFilePath: string;

  private indentation: string = '  ';

  /**
   * Initialize model introspection schema file name and location
   */
  constructor(private readonly functionName: string) {
    this.misFilePath = `${process.cwd()}/.amplify/generated/model-introspection-schema/${
      this.functionName
    }.json`;
  }
  /**
   * Generate a model introspection schema
   */
  generateModelIntrospectionSchema = (modelIntrospectionSchema: string) => {
    this.writeFile(modelIntrospectionSchema);
  };

  /**
   * Check if the script content has a model-introspection-schema import
   * @param scriptContent script content to check
   * @returns true if the script content has a model-introspection-schema import, false otherwise
   */
  usedBy(scriptContent: string) {
    // Matches an import of model-introspection-schema
    const misImportRegex = /import.*from.*model-introspection-schema/g;
    return misImportRegex.test(scriptContent);
  }

  private writeFile = (content: string) => {
    const misFileDirname = path.dirname(this.misFilePath);

    if (!fs.existsSync(misFileDirname)) {
      fs.mkdirSync(misFileDirname, { recursive: true });
    }

    fs.writeFileSync(this.misFilePath, content);
  };
}
