import fs from 'fs';
import path from 'path';

const lambdaDataConfigTemplate = (
  functionName: string
) => `// This file is auto-generated by Amplify. Edits will be overwritten.
import { getAmplifyClientsConfiguration } from "@aws-amplify/backend-function/runtime";
import { env } from "../env/${functionName}";
export const { libraryOptions, resourceConfig } = await getAmplifyClientsConfiguration(env);
`;

/**
 * Generates the data configuration imports
 */
export class FunctionDataConfigGenerator {
  private typeDefFilePath: string;

  private indentation: string = '  ';

  /**
   * Initialize data configuration file name and location
   */
  constructor(private readonly functionName: string) {
    this.typeDefFilePath = `${process.cwd()}/.amplify/generated/data-config/${
      this.functionName
    }.ts`;
  }

  /**
   * Generate data-config shim
   */
  generateDataConfigShim = () => {
    this.writeShimFile(lambdaDataConfigTemplate(this.functionName));
  };

  private writeShimFile = (content: string) => {
    const typeDefFileDirname = path.dirname(this.typeDefFilePath);

    if (!fs.existsSync(typeDefFileDirname)) {
      fs.mkdirSync(typeDefFileDirname, { recursive: true });
    }

    fs.writeFileSync(this.typeDefFilePath, content);
  };
}
