name: select_e2e_account
description: Selects random e2e account
inputs:
  e2e_test_accounts:
    description: Serialized JSON array of strings with account numbers
outputs:
  e2e_test_account_number:
    description: 'Selected e2e account'
    value: ${{ steps.selectE2EAccount.outputs.e2e_test_account_number }}
  e2e_execution_role:
    description: "Selected e2e account's execution role"
    value: ${{ steps.outputE2ERoles.outputs.e2e_execution_role }}
  e2e_test_tooling_role:
    description: "Selected e2e account's test tooling role"
    value: ${{ steps.outputE2ERoles.outputs.e2e_test_tooling_role }}
runs:
  using: composite
  steps:
    - name: Select E2E test account
      id: selectE2EAccount
      shell: bash
      run: echo "e2e_test_account_number=$(npx tsx scripts/select_e2e_test_account.ts)" >> "$GITHUB_OUTPUT"
      env:
        E2E_TEST_ACCOUNTS: ${{ inputs.e2e_test_accounts }}
    - name: Output E2E roles
      id: outputE2ERoles
      shell: bash
      run: |
        echo "e2e_execution_role=arn:aws:iam::${{ steps.selectE2EAccount.outputs.e2e_test_account_number }}:role/e2e-execution" >> "$GITHUB_OUTPUT"
        echo "e2e_test_tooling_role=arn:aws:iam::${{ steps.selectE2EAccount.outputs.e2e_test_account_number }}:role/e2e-test-tooling" >> "$GITHUB_OUTPUT"
