import { AuthClientConfig } from './auth_client_config.js';
import { GraphqlClientConfig } from './graphql_client_config.js';
import { PlatformClientConfig } from './platform_client_config.js';
import { StorageClientConfig } from './storage_client_config.js';
import { CustomClientConfig } from './custom_client_config.js';
import { GeoClientConfig } from './geo_client_config.js';
import { RestApiClientConfig } from './rest_api_client_config.js';
import { AnalyticsClientConfig } from './analytics_client_config.js';
import { NotificationsClientConfig } from './notifications_client_config.js';

// Versions of Gen2 config schemas
import * as clientConfigTypesV1 from '../client-config-schema/client_config_v1.js';

/**
 * Merged type of all category client config legacy types
 */
export type ClientConfigLegacy = Partial<
  AnalyticsClientConfig &
    AuthClientConfig &
    GeoClientConfig &
    GraphqlClientConfig &
    NotificationsClientConfig &
    RestApiClientConfig &
    StorageClientConfig &
    PlatformClientConfig &
    CustomClientConfig
>;

/**
 * Versions of client config schema supported by "this" package version.
 * Create union for supported versions here, such as
 * ClientConfig = clientConfigTypesV1.AWSAmplifyGen2BackendOutputs | clientConfigTypesV2.AWSAmplifyGen2BackendOutputs;
 */
export type ClientConfig = clientConfigTypesV1.AWSAmplifyBackendOutputs;

export { clientConfigTypesV1 };

export enum ClientConfigVersions {
  LEGACY = '0',
  V1 = '1',
}

export type ClientConfigVersion = `${ClientConfigVersions}`;

// Client config version that is generated by default if customers didn't specify one
export const DEFAULT_CLIENT_CONFIG: ClientConfigVersion =
  ClientConfigVersions.LEGACY;

// Client config version that is used by `backend.addOutput()`
export const DEFAULT_CLIENT_CONFIG_VERSION_FOR_BACKEND_ADD_OUTPUT =
  ClientConfigVersions.V1;

/**
 * Return type of `getClientConfig`. This types narrow the returned client config version
 * if the caller specified a static version, e.g. `generateClientConfig(_, _, ClientConfigVersions.V1)`
 *
 * Add new supported version here such as
 * export type ClientConfigVersionType<T> = T extends '1'
 * ? clientConfigTypesV1.AWSAmplifyGen2BackendOutputs
 * : T extends '2'
 * ? clientConfigTypesV2.ClientConfigV2
 * : never;
 */
export type ClientConfigVersionType<T> = T extends '1'
  ? clientConfigTypesV1.AWSAmplifyBackendOutputs
  : never;

export enum ClientConfigFormat {
  MJS = 'mjs',
  JSON = 'json',
  JSON_MOBILE = 'json-mobile',
  TS = 'ts',
  DART = 'dart',
}

export enum ClientConfigFileName {
  LEGACY = 'amplifyconfiguration',
  DEFAULT = 'amplify-outputs',
}
