name: build_with_latest_dependencies
description: builds the source code with latest dependencies
runs:
  using: composite
  steps:
    - name: Install and build without lock file
      shell: bash
      run: |
        rm package-lock.json
        npm install
        npm run build
