import { describe, it, mock } from 'node:test';
import fs from 'fs';
import fsp from 'fs/promises';
import assert from 'assert';
import { pathToFileURL } from 'url';
import { SecretNamesGenerator } from './secret_names_generator.js';

void describe('FunctionEnvironmentTypeGenerator', () => {
  void it('generates a type definition file', () => {
    const fdCloseMock = mock.fn();
    const fsOpenSyncMock = mock.method(fs, 'openSync');
    const fsWriteFileSyncMock = mock.method(fs, 'writeFileSync', () => null);
    fsOpenSyncMock.mock.mockImplementation(() => {
      return {
        close: fdCloseMock,
      };
    });
    const secretNamesGenerator = new SecretNamesGenerator();

    secretNamesGenerator.generateTypeForSecretNames(['secret1', 'secret2']);

    // assert type definition file path
    assert.equal(
      fsWriteFileSyncMock.mock.calls[0].arguments[0],
      `${process.cwd()}/.amplify/generated/secrets.ts`
    );
    // assert content
    const expectedContent = `// This file is auto-generated by Amplify. Edits will be overwritten.

/** This file contains the list of secret names added via \`npx amplify sandbox secret set <secretName>\` */
declare module "@aws-amplify/backend-secret" {
  type SecretName = { 
    name: "secret1" | "secret2";
  };

};
`;
    assert.deepStrictEqual(
      fsWriteFileSyncMock.mock.calls[0].arguments[1]?.toString(),
      expectedContent
    );

    mock.restoreAll();
  });

  void it('generated type definition file has valid syntax', async () => {
    const targetDirectory = await fsp.mkdtemp('func_env_type_gen_test');
    const secretNamesGenerator = new SecretNamesGenerator();
    const filePath = `${process.cwd()}/.amplify/generated/secrets.ts`;

    secretNamesGenerator.generateTypeForSecretNames(['TEST_ENV']);

    // import to validate syntax of type definition file
    await import(pathToFileURL(filePath).toString());

    await fsp.rm(targetDirectory, { recursive: true, force: true });
  });
});
