import fs from 'fs';
import path from 'path';
import { EOL } from 'os';

/**
 * Generates a typed process.env shim for environment variables
 */
export class SecretNamesGenerator {
  private readonly header =
    '// This file is auto-generated by Amplify. Edits will be overwritten.';

  private filePath = `${process.cwd()}/.amplify/generated/secrets.ts`;

  /**
   * Generate a file that add types to the @aws-amplify/backend-secret:SecretName to aid
   * with surfacing errors related to non-existent secrets
   */
  generateTypeForSecretNames(secretNames: string[]) {
    const codeLines = [];

    // Add Lambda runtime environment variables to the typed shim
    codeLines.push(
      '/** This file contains the list of secret names added via `npx amplify sandbox secret set <secretName>` */'
    );
    codeLines.push(`declare module "@aws-amplify/backend-secret" {`);
    codeLines.push(`  type SecretName = { `);
    codeLines.push(
      `    name: ${secretNames.map((name) => `"${name}"`).join(' | ')};`
    );
    codeLines.push(`  };${EOL}`);
    codeLines.push(`};${EOL}`);

    const content = `${this.header}${EOL}${EOL}${codeLines.join(EOL)}`;

    this.writeShimFile(content);
  }

  private writeShimFile = (content: string) => {
    const directory = path.dirname(this.filePath);

    if (!fs.existsSync(directory)) {
      fs.mkdirSync(directory, { recursive: true });
    }

    fs.writeFileSync(this.filePath, content);
  };
}
