allow-licenses:
  - 0BSD
  - Apache-2.0
  - BSD-1-Clause
  - BSD-2-Clause-FreeBSD
  - BSD-2-Clause
  - BSD-3-Clause-Attribution
  - BSD-3-Clause
  - BSD-Source-Code
  - bzip2-1.0.6
  - CC-BY-3.0
  - CC-BY-4.0
  - curl
  - ISC
  - JSON
  - MIT
  - NTP
  - OLDAP-2.8
  - OpenSSL
  - PDDL-1.0
  - PostgreSQL
  - Python-2.0
  - Spencer-94
  - Unicode-DFS-2015
  - Unicode-DFS-2016
  - Unlicense
  - WTFPL
  - X11
  - zlib-acknowledgement
  - Zlib
# Skip our packages under packages/ as they don't have their own license file and are treated as if they don't have a license
allow-dependencies-licenses:
  - pkg:npm/aws-amplify/amplify-backend#packages/ampx
  - pkg:npm/aws-amplify/amplify-backend#packages/auth-construct
  - pkg:npm/aws-amplify/amplify-backend#packages/backend
  - pkg:npm/aws-amplify/amplify-backend#packages/backend-auth
  - pkg:npm/aws-amplify/amplify-backend#packages/backend-data
  - pkg:npm/aws-amplify/amplify-backend#packages/backend-deployer
  - pkg:npm/aws-amplify/amplify-backend#packages/backend-function
  - pkg:npm/aws-amplify/amplify-backend#packages/backend-output-schemas
  - pkg:npm/aws-amplify/amplify-backend#packages/backend-output-storage
  - pkg:npm/aws-amplify/amplify-backend#packages/backend-secret
  - pkg:npm/aws-amplify/amplify-backend#packages/backend-storage
  - pkg:npm/aws-amplify/amplify-backend#packages/cli
  - pkg:npm/aws-amplify/amplify-backend#packages/cli-core
  - pkg:npm/aws-amplify/amplify-backend#packages/client-config
  - pkg:npm/aws-amplify/amplify-backend#packages/create-amplify
  - pkg:npm/aws-amplify/amplify-backend#packages/deployed-backend-client
  - pkg:npm/aws-amplify/amplify-backend#packages/form-generator
  - pkg:npm/aws-amplify/amplify-backend#packages/platform-core
  - pkg:npm/aws-amplify/amplify-backend#packages/plugin-types
  - pkg:npm/aws-amplify/amplify-backend#packages/sandbox
  - pkg:npm/aws-amplify/amplify-backend#packages/schema-generator
