name: install_with_cache
description: installs node_modules if cache miss and stores in the cache
inputs:
  node-version:
    default: 18
  cdk-version:
    required: false
runs:
  using: composite
  steps:
    # cache node_modules based on package-lock.json hash
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # version 4.0.2
      id: npm-cache
      with:
        path: |
          node_modules
          packages/**/node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}-node${{ inputs.node-version }}-cdk${{ inputs.cdk-version }}
    # only install if cache miss
    - if: steps.npm-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npm ci
        if [ ! -z "${{ inputs.cdk-version }}" ]; then
          echo "Installing CDK version ${{ inputs.cdk-version }}"
          npm install aws-cdk@${{ inputs.cdk-version }} aws-cdk-lib@${{ inputs.cdk-version }}
          npx cdk --version
        fi
