export type LogRetention =
  | '1 day'
  | '3 days'
  | '5 days'
  | '1 week'
  | '2 weeks'
  | '1 month'
  | '2 months'
  | '3 months'
  | '4 months'
  | '5 months'
  | '6 months'
  | '1 year'
  | '13 months'
  | '18 months'
  | '2 years'
  | '3 years'
  | '5 years'
  | '6 years'
  | '7 years'
  | '8 years'
  | '9 years'
  | '10 years'
  | 'infinite';
