import assert from 'assert';
import fsp from 'fs/promises';
import { afterEach, describe, it, mock } from 'node:test';
import path from 'path';
import { YarnClassicLockFileReader } from './yarn_classic_lock_file_reader.js';

void describe('YarnClassicLockFileReader', () => {
  const fspReadFileMock = mock.method(
    fsp,
    'readFile',
    () => `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@test_dep@^1.0.0":
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/some_dep"
  integrity some-sha
  dependencies:
    "sub_dep_1" "^0.3.5"
    "sub_dep_2" "^0.3.24"

some_other_dep@12.13.14:
  version "12.13.14"
  resolved "https://registry.yarnpkg.com/some_other_dep"
  integrity some-other-sha
  dependencies:
    sub_dep_3 "~2.0.1"`
  );
  const yarnClassicLockFileReader = new YarnClassicLockFileReader();

  afterEach(() => {
    fspReadFileMock.mock.resetCalls();
  });

  void it('can get lock file contents from cwd', async () => {
    const lockFileContents =
      await yarnClassicLockFileReader.getLockFileContentsFromCwd();
    const expectedLockFileContents = {
      dependencies: [
        {
          name: '@test_dep',
          version: '1.2.3',
        },
        {
          name: 'some_other_dep',
          version: '12.13.14',
        },
      ],
    };
    assert.deepEqual(lockFileContents, expectedLockFileContents);
    assert.strictEqual(
      fspReadFileMock.mock.calls[0].arguments[0],
      path.resolve(process.cwd(), 'yarn.lock')
    );
    assert.strictEqual(fspReadFileMock.mock.callCount(), 1);
  });

  void it('returns undefined when yarn.lock is not present or parse-able', async () => {
    fspReadFileMock.mock.mockImplementationOnce(() =>
      Promise.reject(new Error())
    );
    const lockFileContents =
      await yarnClassicLockFileReader.getLockFileContentsFromCwd();
    assert.deepEqual(lockFileContents, undefined);
  });

  void it('returns empty dependency array when yarn.lock does not have dependencies', async () => {
    mock.method(
      fsp,
      'readFile',
      () => `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


`
    );
    const lockFileContents =
      await yarnClassicLockFileReader.getLockFileContentsFromCwd();
    assert.deepEqual(lockFileContents, { dependencies: [] });
  });
});
