import { Construct } from 'constructs';
import {
  BackendIdentifier,
  BackendSecret,
  ResolvePathResult,
} from '@aws-amplify/plugin-types';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import { RemovalPolicy, SecretValue } from 'aws-cdk-lib';
import { ParameterPathConversions } from '@aws-amplify/platform-core';
import { SecurityConfig, VpcConfig } from './types.js';

/**
 * Adapts a connection URI string to the {@link BackendSecret} interface.
 *
 * The SQL Lambda resolves its database connection URI from SSM at runtime,
 * looking up paths generated by {@link ParameterPathConversions}. This class
 * pre-computes those paths from the {@link BackendIdentifier} so that
 * {@link resolvePath} is a pure getter with no side effects.
 *
 * The actual SSM SecureString parameters are created by {@link AuroraConstruct}
 * in its constructor — not by this class.
 */
class SsmParameterBackendSecret implements BackendSecret {
  /** SSM path scoped to the current branch/sandbox deployment */
  readonly branchSecretPath: string;
  /** SSM path shared across all deployments in the namespace */
  readonly sharedSecretPath: string;

  constructor(
    private readonly connectionUri: string,
    backendIdentifier: BackendIdentifier,
    secretName: string,
  ) {
    this.branchSecretPath = ParameterPathConversions.toParameterFullPath(
      backendIdentifier,
      secretName,
    );
    this.sharedSecretPath = ParameterPathConversions.toParameterFullPath(
      backendIdentifier.namespace,
      secretName,
    );
  }

  /**
   * Resolves the connection URI as a CDK SecretValue.
   */
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  resolve(scope: Construct, backendIdentifier: BackendIdentifier): SecretValue {
    return SecretValue.unsafePlainText(this.connectionUri);
  }

  /**
   * Returns pre-computed SSM parameter paths. Pure getter — no side effects.
   */
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  resolvePath(backendIdentifier: BackendIdentifier): ResolvePathResult {
    return {
      branchSecretPath: this.branchSecretPath,
      sharedSecretPath: this.sharedSecretPath,
    };
  }
}

export type AuroraConstructProps = {
  /** Name of the PostgreSQL database to create */
  databaseName: string;
  /** Minimum Aurora Capacity Units (ACUs) for Serverless v2 scaling */
  minCapacity: number;
  /** Maximum Aurora Capacity Units (ACUs) for Serverless v2 scaling */
  maxCapacity: number;
  /** Existing VPC ID to deploy into. If omitted, a new VPC is created. */
  vpcId?: string;
  /** Backend identifier used to generate Amplify-standard SSM parameter paths */
  backendIdentifier: BackendIdentifier;
};

/**
 * CDK construct that provisions an Aurora Serverless v2 PostgreSQL cluster
 * with all required networking infrastructure.
 *
 * Creates: VPC (or uses existing), security group with self-referencing rules,
 * Aurora cluster, Secrets Manager credentials, and SSM SecureString parameters
 * for the connection URI at Amplify-standard paths.
 *
 * Networking architecture:
 * - VPC with natGateways=0 (public + isolated subnets, no NAT costs)
 * - Aurora writer in public subnets (publiclyAccessible for dev/sandbox)
 * - SQL Lambda runs in isolated subnets with VPC endpoints for SSM access
 * - Shared security group with self-referencing rules for ports 443 and 5432
 */
export class AuroraConstruct extends Construct {
  readonly cluster: rds.DatabaseCluster;
  readonly vpc: ec2.IVpc;
  readonly securityGroup: ec2.SecurityGroup;
  readonly connectionSecret: BackendSecret;

  /**
   * Creates an Aurora Serverless v2 cluster with networking and secret storage.
   *
   * The constructor creates all CDK resources including SSM parameters.
   * No resources are created lazily or via side effects in other methods.
   */
  constructor(scope: Construct, id: string, props: AuroraConstructProps) {
    super(scope, id);

    // Get or create VPC
    this.vpc = props.vpcId
      ? ec2.Vpc.fromLookup(this, 'Vpc', { vpcId: props.vpcId })
      : new ec2.Vpc(this, 'Vpc', {
          maxAzs: 2,
          natGateways: 0, // Use VPC endpoints to avoid NAT costs
        });

    // Create security group for Aurora
    this.securityGroup = new ec2.SecurityGroup(this, 'AuroraSecurityGroup', {
      vpc: this.vpc,
      description: 'Security group for Aurora Serverless v2',
      allowAllOutbound: true,
    });

    // Self-referencing ingress rules: the SQL Lambda, VPC endpoints, and Aurora
    // all share this security group. Without these rules, Lambda cannot reach
    // SSM VPC endpoints (443) or the Aurora cluster (5432).
    this.securityGroup.addIngressRule(
      this.securityGroup,
      ec2.Port.tcp(443),
      'Allow HTTPS from Lambda to VPC endpoints',
    );

    this.securityGroup.addIngressRule(
      this.securityGroup,
      ec2.Port.tcp(5432),
      'Allow PostgreSQL from Lambda',
    );

    // Create database credentials secret
    const secret = new secretsmanager.Secret(this, 'AuroraSecret', {
      generateSecretString: {
        secretStringTemplate: JSON.stringify({ username: 'postgres' }),
        generateStringKey: 'password',
        excludePunctuation: true,
        includeSpace: false,
      },
    });

    // Create Aurora Serverless v2 cluster
    this.cluster = new rds.DatabaseCluster(this, 'AuroraCluster', {
      engine: rds.DatabaseClusterEngine.auroraPostgres({
        version: rds.AuroraPostgresEngineVersion.of('15.8', '15'),
      }),
      credentials: rds.Credentials.fromSecret(secret),
      defaultDatabaseName: props.databaseName,
      vpc: this.vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PUBLIC, // Use public subnets since we have no NAT
      },
      securityGroups: [this.securityGroup],
      writer: rds.ClusterInstance.serverlessV2('writer', {
        autoMinorVersionUpgrade: true,
        publiclyAccessible: true, // Required for public subnet
      }),
      serverlessV2MinCapacity: props.minCapacity,
      serverlessV2MaxCapacity: props.maxCapacity,
      removalPolicy: RemovalPolicy.SNAPSHOT,
    });

    // Build proper PostgreSQL connection URI
    const username = secret.secretValueFromJson('username').unsafeUnwrap();
    const password = secret.secretValueFromJson('password').unsafeUnwrap();
    const host = this.cluster.clusterEndpoint.hostname;
    const port = this.cluster.clusterEndpoint.port;
    const database = props.databaseName;

    const connectionUri = `postgresql://${username}:${password}@${host}:${port}/${database}`;

    // Create BackendSecret wrapper with pre-computed paths
    const secretName = 'AURORA_CONNECTION_URI';
    const connectionSecretWrapper = new SsmParameterBackendSecret(
      connectionUri,
      props.backendIdentifier,
      secretName,
    );

    // SSM SecureString parameters at Amplify-standard paths.
    // The SQL Lambda reads its connection URI from these paths at runtime
    // via VPC endpoints. Both branch-scoped and shared paths are created
    // so the Lambda can fall back to the shared path across deployments.
    new ssm.CfnParameter(this, 'BranchConnectionUriParameter', {
      name: connectionSecretWrapper.branchSecretPath,
      value: connectionUri,
      type: 'SecureString',
    });
    new ssm.CfnParameter(this, 'SharedConnectionUriParameter', {
      name: connectionSecretWrapper.sharedSecretPath,
      value: connectionUri,
      type: 'SecureString',
    });

    this.connectionSecret = connectionSecretWrapper;
  }

  /**
   * Get VPC configuration for Lambda functions
   */
  getVpcConfig(): VpcConfig {
    return {
      vpc: this.vpc,
      securityGroups: [this.securityGroup],
      allowPublicSubnet: false,
    };
  }

  /**
   * Get security configuration for database access
   */
  getSecurityConfig(): SecurityConfig {
    return {
      allowedSecurityGroups: [this.securityGroup],
    };
  }
}
