name: run_with_e2e_account
description: Runs commands with e2e test account
inputs:
  run:
    description: Script to run
    required: true
  shell:
    description: Shell
    required: false
  node_version:
    description: node version used to configure environment with
    required: true
  e2e_test_accounts:
    description: Serialized JSON array of strings with account numbers
    required: true
  aws_region:
    description: AWS region. If not provided random will be selected
    required: false
  link_cli:
    description: Whether should link Gen2 CLI globally
    default: false
  fresh_build:
    description: Whether should build from scratch
    default: false
  cdk-lib-version:
    required: true
  retry_attempts:
    description: Number of retry attempts for the main script
    required: false
    default: '5'
  retry_delay:
    description: Delay between retry attempts in seconds
    required: false
    default: '300'
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: ./.github/actions/setup_node
      with:
        node-version: ${{ inputs.node_version }}
    - name: Restore Build Cache
      if: inputs.fresh_build != 'true'
      uses: ./.github/actions/restore_build_cache
      with:
        cdk-lib-version: ${{ inputs.cdk-lib-version }}
        node-version: ${{ inputs.node_version }}
    - name: Build With Cache
      if: inputs.fresh_build == 'true'
      uses: ./.github/actions/build_with_cache
      with:
        cdk-lib-version: ${{ inputs.cdk-lib-version }}
        node-version: ${{ inputs.node_version }}
    - name: Link CLI
      if: inputs.link_cli == 'true'
      shell: bash
      run: cd packages/cli && npm link
    - name: Select E2E test account
      uses: ./.github/actions/select_e2e_account
      id: selectE2EAccount
      with:
        e2e_test_accounts: ${{ inputs.e2e_test_accounts }}
    - name: Select region
      id: selectE2ERegion
      shell: bash
      run: |
        if [ -z "${{ inputs.aws_region }}" ]; then
          regions=("us-west-2" "us-east-1" "ca-central-1" "eu-central-1")
          rand=$[$RANDOM % ${#regions[@]}]
          selected_aws_region=${regions[$rand]}
        else
          selected_aws_region="${{ inputs.aws_region }}"
        fi
        echo "Selected AWS Region is $selected_aws_region"
        echo "selected_aws_region=$selected_aws_region" >> "$GITHUB_OUTPUT"
    - name: Configure test tooling credentials
      uses: ./.github/actions/setup_profile
      with:
        role-to-assume: ${{ steps.selectE2EAccount.outputs.e2e_test_tooling_role }}
        aws-region: ${{ steps.selectE2ERegion.outputs.selected_aws_region }}
        profile-name: e2e-tooling
    - name: Configure test execution credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # version 4.0.2
      with:
        role-to-assume: ${{ steps.selectE2EAccount.outputs.e2e_execution_role }}
        aws-region: ${{ steps.selectE2ERegion.outputs.selected_aws_region }}
    - name: Run script with retry
      shell: bash
      run: |
        set -e

        # Set default shell if not provided
        SHELL_CMD="${{ inputs.shell }}"
        if [ -z "$SHELL_CMD" ]; then
          SHELL_CMD="bash"
        fi

        # Retry logic
        RETRY_ATTEMPTS=${{ inputs.retry_attempts }}
        RETRY_DELAY=${{ inputs.retry_delay }}
        ATTEMPT=1

        while [ $ATTEMPT -le $RETRY_ATTEMPTS ]; do
          echo "Attempt $ATTEMPT of $RETRY_ATTEMPTS"
          
          if [ "$SHELL_CMD" = "bash" ]; then
            if bash -c '${{ inputs.run }}'; then
              echo "Script succeeded on attempt $ATTEMPT"
              exit 0
            fi
          elif [ "$SHELL_CMD" = "pwsh" ]; then
            if pwsh -c '${{ inputs.run }}'; then
              echo "Script succeeded on attempt $ATTEMPT"
              exit 0
            fi
          else
            # Default to bash for other shells
            if bash -c '${{ inputs.run }}'; then
              echo "Script succeeded on attempt $ATTEMPT"
              exit 0
            fi
          fi
          
          if [ $ATTEMPT -lt $RETRY_ATTEMPTS ]; then
            echo "Script failed on attempt $ATTEMPT. Retrying in $RETRY_DELAY seconds..."
            sleep $RETRY_DELAY
          else
            echo "Script failed after $RETRY_ATTEMPTS attempts"
            exit 1
          fi
          
          ATTEMPT=$((ATTEMPT + 1))
        done
      env:
        AWS_REGION: ${{ steps.selectE2ERegion.outputs.selected_aws_region }}
        AMPLIFY_BACKEND_TESTS_E2E_EXECUTION_ROLE_ARN: ${{ steps.selectE2EAccount.outputs.e2e_execution_role }}
