# basic setup that applies to most jobs
# checks out the repo and configures node
name: checkout_and_setup_node
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
