# restores node_modules from the cache
# fails if no cache entry found
name: restore_install_cache
runs:
  using: composite
  steps:
    # restore node_modules from cache
    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        fail-on-cache-miss: true
