name: restore_install_cache
description: restores node_modules from the cache and fails if no cache entry found
inputs:
  node-version:
    description: node version used to configure environment with
    required: true
  cdk-version:
    required: true
runs:
  using: composite
  steps:
    # Validate that non-blank inputs are provided.
    # This is to ensure that inputs are plumbed and not defaulted accidentally in action call chains.
    # The 'required' input property does not assert this if value is provided at runtime.
    - name: Validate input
      shell: bash
      run: |
        if [ -z "${{ inputs.cdk-version }}" ]; then
          echo "CDK version must be provided"
          exit 1;
        fi
        if [ -z "${{ inputs.node-version }}" ]; then
          echo "Node version must be provided"
          exit 1;
        fi
    # restore node_modules from cache
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # version 4.0.2
      id: npm-cache
      with:
        path: |
          node_modules
          packages/**/node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}-node${{ inputs.node-version }}-cdk${{ inputs.cdk-version }}
        fail-on-cache-miss: true
