name: restore_install_cache
description: restores node_modules from the cache and fails if no cache entry found
inputs:
  node-version:
    description: node version used to configure environment with
    default: 18
runs:
  using: composite
  steps:
    - name: Locate local NPM cache
      id: locate-local-npm-cache
      shell: bash
      run: |
        echo "$(npm config get cache)"
        echo "npm_cache_path=$(npm config get cache)" >> "$GITHUB_OUTPUT"
    # restore node_modules from cache
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # version 4.0.2
      id: npm-cache
      with:
        path: |
          node_modules
          packages/**/node_modules
          ${{ steps.locate-local-npm-cache.outputs.npm_cache_path }}
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}-node${{ inputs.node-version }}-v2
        fail-on-cache-miss: true
