name: restore_build_cache
description: composes restoring node_modules and restoring build artifacts
inputs:
  node-version:
    description: node version used to configure environment with
    required: true
  cdk-lib-version:
    required: true
  cdk-cli-version:
    required: true
runs:
  using: composite
  steps:
    # Validate that non-blank inputs are provided.
    # This is to ensure that inputs are plumbed and not defaulted accidentally in action call chains.
    # The 'required' input property does not assert this if value is provided at runtime.
    - name: Validate input
      shell: bash
      run: |
        if [ -z "${{ inputs.cdk-lib-version }}" ]; then
          echo "CDK Lib version must be provided"
          exit 1;
        fi
        if [ -z "${{ inputs.cdk-cli-version }}" ]; then
          echo "CDK CLI version must be provided"
          exit 1;
        fi
        if [ -z "${{ inputs.node-version }}" ]; then
          echo "Node version must be provided"
          exit 1;
        fi
    - uses: ./.github/actions/restore_install_cache
      with:
        node-version: ${{ inputs.node-version }}
        cdk-lib-version: ${{ inputs.cdk-lib-version }}
        cdk-cli-version: ${{ inputs.cdk-cli-version }}
    # restore build output from cache
    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # version 4.2.0
      id: build-cache
      with:
        path: '**/lib'
        key: ${{ github.sha }}-node${{ inputs.node-version }}-cdklib${{ inputs.cdk-lib-version }}-cdkcli${{ inputs.cdk-cli-version }}
        fail-on-cache-miss: true
        enableCrossOsArchive: true
