name: restore_build_cache
description: composes restoring node_modules and restoring build artifacts
inputs:
  node-version:
    description: node version used to configure environment with
    default: 18
  cdk-version:
    # This is intentionally required to assert that CDK version is plumbed through.
    required: true
runs:
  using: composite
  steps:
    - uses: ./.github/actions/restore_install_cache
      with:
        node-version: ${{ inputs.node-version }}
        cdk-version: ${{ inputs.cdk-version }}
    # restore build output from cache
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # version 4.0.2
      id: build-cache
      with:
        path: '**/lib'
        key: ${{ github.sha }}-node${{ inputs.node-version }}-cdk${{ inputs.cdk-version }}
        fail-on-cache-miss: true
        enableCrossOsArchive: true
