# basic setup that applies to most jobs
# checks out the repo and configures node
name: setup_node
runs:
  using: composite
  steps:
    - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # version 3.8.1
      with:
        node-version: 18
        cache: 'npm'
