/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// This file is not supposed to be in git. It's committed in example app for reference.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_appsync_graphqlEndpoint: 'https://my.awesome.endpoint/graphql',
  aws_appsync_region: 'us-west-2',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'REDACTED',
};

export default awsmobile;
