name: check_pr_size

on:
  pull_request:
    branches: ['main']

jobs:
  check_pr_size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: git fetch origin
      - run: npm run diff:check refs/pull/${{ github.event.pull_request.number }}/head refs/pull/${{ github.event.pull_request.number }}/merge
