name: dependency_review

on:
  pull_request:
    branches:
      - main
      - hotfix
      - feature/**

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # version 3.6.0
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          config-file: ./.github/dependency_review_config.yml
