name: deprecate_release

on:
  push:
    branches:
      - rollback
  workflow_dispatch:
    inputs:
      commitHash:
        required: true
        type: string
      deprecationMessage:
        required: true
        type: string

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # version 3.6.0
      - uses: ./.github/actions/setup_node
      - uses: ./.github/actions/install_with_cache
  deprecate_release:
    needs:
      - install
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # version 3.6.0
      - uses: ./.github/actions/setup_node
      - uses: ./.github/actions/restore_install_cache
      - name: Deprecate release versions
        run: npx tsx scripts/deprecate_release.ts --commit-hash ${{ inputs.commitHash }} --deprecation-message ${{ inputs.deprecationMessage }}
